// JsViewerSamples/JSViewer_Angular_Core/ClientApp/src/app/report-viewer/report-viewer.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { JSViewer, createViewer} from '@grapecity/ar-viewer';

@Component({
  selector: 'report-viewer',
  templateUrl: './report-viewer.component.html',
  styleUrls: [
      './report-viewer.component.css',
      '../../../node_modules/@grapecity/ar-viewer/dist/jsViewer.min.css'
  ],
  encapsulation: ViewEncapsulation.None,
})
export class ReportViewerComponent {
  private viewer: JSViewer | null = null;

  @Input() set reportId(reportId: string) {
      if (!this.viewer) {
          this.viewer = createViewer({
              element: '#viewerPlaceHolder'
          });
      }

      this.viewer.openReport(reportId);
  }
}

// JsViewerSamples/JSViewer_React_Hooks/ClientApp/src/reportViewer.tsx
import * as React from "react";

import { JSViewer, createViewer} from '@grapecity/ar-viewer';
import "@grapecity/ar-viewer/dist/jsViewer.min.css";

export const ReportViewer: React.FC<{ reportId: string }> = ({ reportId }) => {
  const [viewerInstance, setViewerInstance] = React.useState<JSViewer | undefined>(undefined);
  React.useEffect(() => {
    if (!viewerInstance) {
      const viewer = createViewer({
        element: "#viewerContainer",
      });
      setViewerInstance(viewer);
    }
    if (reportId) {
      viewerInstance?.openReport(reportId);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reportId]);
  return <div id="viewerContainer" />;
};
